server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/ecommerce-realm
          jwk-set-uri: http://localhost:8083/realms/ecommerce-realm/protocol/openid-connect/certs
